"""initial schema

Revision ID: f93b4b48fcc6
Revises: 
Create Date: 2026-09-20 12:49:25.688462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f93b4b48fcc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('public', 'confidential', name='client_type'), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=True),
    sa.Column('redirect_uris', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('post_logout_redirect_uris', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_grants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('require_consent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limits',
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bucket')
    )
    op.create_table('signing_keys',
    sa.Column('kid', sa.String(), nullable=False),
    sa.Column('alg', sa.String(), nullable=False),
    sa.Column('public_jwk', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('private_pem_encrypted', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('next', 'active', 'retired', name='key_status'), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kid')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('numero_fiscal', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'agent', 'contribuable', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('pending_activation', 'active', 'locked', 'disabled', name='user_status'), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('numero_fiscal')
    )
    # ADR §8: email uniqueness is case-insensitive ("unique sur lower(email)") —
    # a functional index, which autogenerate cannot express as a plain column
    # constraint.
    op.execute("CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email))")
    op.create_table('activation_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', postgresql.INET(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('code_challenge', sa.String(), nullable=False),
    sa.Column('code_challenge_method', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', postgresql.INET(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_label', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(), nullable=True),
    sa.Column('acr', sa.String(), nullable=False),
    sa.Column('amr', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_ip', postgresql.INET(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.Enum('success', 'failure', name='outcome'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id', 'occurred_at'),
    postgresql_partition_by='RANGE (occurred_at)'
    )
    # A partitioned table with zero partitions rejects every insert — one default
    # partition catches everything until real per-period partitions are added later.
    op.execute("CREATE TABLE audit_events_default PARTITION OF audit_events DEFAULT")
    # ADR §8: append-only at the privilege level, not just by convention — even a
    # bug or SQL injection in auth-server can't erase or alter an audit trail.
    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM authentint_app")
    op.create_table('authorization_codes',
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('code_challenge', sa.String(), nullable=False),
    sa.Column('code_challenge_method', sa.String(), nullable=False),
    sa.Column('auth_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acr', sa.String(), nullable=False),
    sa.Column('amr', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['parent_hash'], ['refresh_tokens.token_hash'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('authorization_codes')
    op.drop_table('audit_events')
    op.drop_table('sessions')
    op.drop_table('password_reset_tokens')
    op.drop_table('interactions')
    op.drop_table('consents')
    op.drop_table('activation_tokens')
    op.drop_table('users')
    op.drop_table('signing_keys')
    op.drop_table('rate_limits')
    op.drop_table('clients')
    # ### end Alembic commands ###
    # Alembic's drop_table() does not drop the native Postgres ENUM types it
    # created for sa.Enum columns — verified by round-tripping downgrade+upgrade,
    # which failed with "type already exists" on the second upgrade otherwise.
    op.execute("DROP TYPE outcome")
    op.execute("DROP TYPE user_status")
    op.execute("DROP TYPE user_role")
    op.execute("DROP TYPE key_status")
    op.execute("DROP TYPE client_type")
